### ISSUE TITLE
Plugin Stop Working on above HFS 0.54

### ISSUE THREAD

**Issue by NanKillBro** [SanokKule/starfield-background#1]
I love this plugin so much, pls fix it

**Comment by SanokKule** [comment]
What browser?
Any errors in browser console?

**Comment by EinsteinIamNot** [comment]
I have same. it stopped working after updating.  there are no errors when i open the console. using latest edge and mozilla firefox. i do not use extensions to block something.
edit:
i owe you an apology, i forgot i am using  version 0.54.0 rc12. when i reverted back to 0.53.2 it was fully working again.

**Comment by SanokKule** [comment]
I see now that it's a change to the hfs styles, it's hidden behind the `background-color` that is set on `html`, when it was on `body` before.
https://github.com/rejetto/hfs/commit/d3c17797cf7ccf0f1ff548db0bc4efc4a5a51dc8
I'll think what i can do

**Comment by SanokKule** [comment]
You can add this to your custom html for now
```
<style>
html {
  background-color: #00000000 !important;
}
</style>
```
![image](https://github.com/user-attachments/assets/73423511-ac5c-4df1-9936-a04438de6f36)

**Comment by EinsteinIamNot** [comment]
yup i tried that, and it worked.  but i had to leave the  <style> and </style> away as i placed in the custom style section
thanks for the fast fix. now works on 0.54.0. rc12

**Comment by SanokKule** [comment]
> but i had to leave the <style> and </style> away as i placed in the custom style section

Right, forgot that exists

**Comment by SanokKule** [comment]
Will be fixed in hfs 0.54

**Comment by rejetto** [comment]
and 0.54 is out, the workaround is no longer necessary

**Comment by EinsteinIamNot** [comment]
removed the fix, tested and confirmed. working. thanks.
